### ISSUE TITLE
Can't import recipes from woolworths.com.au

### ISSUE THREAD

**Issue by picto3000** [hay-kot/mealie#155]
**Describe the bug**
Import is working for all sites except woolworths.com.au, and last_recipe.json is not being updated on woolworths imports

**Steps To Reproduce**
1. Attempt to import: https://www.woolworths.com.au/shop/recipedetail/11047/easy-chicken-satay
2. Error received: "Looks like there was an error parsing the URL. Check the log and debug/last_recipe.json to see what went wrong."
3. Look at last_recipe.json and it has not been updated since the last "good" import I performed.

**Device Information (please complete the following information):**
 - OS: MacOS 11.2.1
 - Deployment: Docker-compose
 - Browser: Safari 14.0.3
 - Version: 0.2.0 (was also an issue on previous releases)

**Log output**
```
today at 9:27 AM  Jobstore default:
today at 9:27 AM      update_webhook_schedule (trigger: interval[0:15:00], next run at: 2021-02-10 22:41:48 UTC)
today at 9:27 AM      webhooks (trigger: cron[hour='0', minute='0'], next run at: 2021-02-11 00:00:00 UTC)
today at 9:27 AM      backups (trigger: cron[hour='0', minute='0'], next run at: 2021-02-11 00:00:00 UTC)
today at 9:27 AM  INFO:     172.19.0.19:40166 - "POST /api/recipes/create-url HTTP/1.1" 500 Internal Server Error
today at 9:27 AM  ERROR:    Exception in ASGI application
today at 9:27 AM  Traceback (most recent call last):
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
today at 9:27 AM      result = await app(self.scope, self.receive, self.send)
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
today at 9:27 AM      return await self.app(scope, receive, send)
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
today at 9:27 AM      await super().__call__(scope, receive, send)
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
today at 9:27 AM      await self.middleware_stack(scope, receive, send)
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
today at 9:27 AM      raise exc from None
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
today at 9:27 AM      await self.app(scope, receive, _send)
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
today at 9:27 AM      raise exc from None
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
today at 9:27 AM      await self.app(scope, receive, sender)
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
today at 9:27 AM      await route.handle(scope, receive, send)
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
today at 9:27 AM      await self.app(scope, receive, send)
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
today at 9:27 AM      response = await func(request)
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
today at 9:27 AM      raw_response = await run_endpoint_function(
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
today at 9:27 AM      return await run_in_threadpool(dependant.call, **values)
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
today at 9:27 AM      return await loop.run_in_executor(None, func, *args)
today at 9:27 AM    File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
today at 9:27 AM      result = self.fn(*self.args, **self.kwargs)
today at 9:27 AM    File "./routes/recipe/recipe_crud_routes.py", line 29, in parse_recipe_url
today at 9:27 AM      recipe = create_from_url(url.url)
today at 9:27 AM    File "./services/scrape_services.py", line 195, in create_from_url
today at 9:27 AM      recipe_data = process_recipe_url(url)
today at 9:27 AM    File "./services/scrape_services.py", line 189, in process_recipe_url
today at 9:27 AM      new_recipe = extract_recipe_from_html(r.text, url)
today at 9:27 AM    File "./services/scrape_services.py", line 140, in extract_recipe_from_html
today at 9:27 AM      new_recipe = basic_recipe_from_opengraph(html, url)
today at 9:27 AM    File "./services/scrape_services.py", line 167, in basic_recipe_from_opengraph
today at 9:27 AM      properties = data["opengraph"][0]["properties"]
today at 9:27 AM  IndexError: list index out of range
today at 9:27 AM  10-Feb-21 22:27:53 ERROR: Exception in ASGI application
today at 9:27 AM  Traceback (most recent call last):
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
today at 9:27 AM      result = await app(self.scope, self.receive, self.send)
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
today at 9:27 AM      return await self.app(scope, receive, send)
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
today at 9:27 AM      await super().__call__(scope, receive, send)
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
today at 9:27 AM      await self.middleware_stack(scope, receive, send)
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
today at 9:27 AM      raise exc from None
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
today at 9:27 AM      await self.app(scope, receive, _send)
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
today at 9:27 AM      raise exc from None
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
today at 9:27 AM      await self.app(scope, receive, sender)
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
today at 9:27 AM      await route.handle(scope, receive, send)
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
today at 9:27 AM      await self.app(scope, receive, send)
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
today at 9:27 AM      response = await func(request)
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
today at 9:27 AM      raw_response = await run_endpoint_function(
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
today at 9:27 AM      return await run_in_threadpool(dependant.call, **values)
today at 9:27 AM    File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
today at 9:27 AM      return await loop.run_in_executor(None, func, *args)
today at 9:27 AM    File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
today at 9:27 AM      result = self.fn(*self.args, **self.kwargs)
today at 9:27 AM    File "./routes/recipe/recipe_crud_routes.py", line 29, in parse_recipe_url
today at 9:27 AM      recipe = create_from_url(url.url)
today at 9:27 AM    File "./services/scrape_services.py", line 195, in create_from_url
today at 9:27 AM      recipe_data = process_recipe_url(url)
today at 9:27 AM    File "./services/scrape_services.py", line 189, in process_recipe_url
today at 9:27 AM      new_recipe = extract_recipe_from_html(r.text, url)
today at 9:27 AM    File "./services/scrape_services.py", line 140, in extract_recipe_from_html
today at 9:27 AM      new_recipe = basic_recipe_from_opengraph(html, url)
today at 9:27 AM    File "./services/scrape_services.py", line 167, in basic_recipe_from_opengraph
today at 9:27 AM      properties = data["opengraph"][0]["properties"]
today at 9:27 AM  IndexError: list index out of range
today at 9:27 AM  INFO:     172.19.0.19:40174 - "GET /api/recipes?keys=name&keys=slug&keys=image&keys=description&keys=dateAdded&keys=rating&num=100 HTTP/1.1" 200 OK
```

**Comment by hay-kot** [comment]
Looks like there's a couple things going on here. When you hit the website it doesn't return any data. Since you get an empty list back from the parser it throws all kinds of errors before the last_recipe gets dumped. I moved some things around to dump the response sooner. That said, since this recipe doesn't return anything you'll just get [] in the last_recipe.json.

**Comment by wengtad** [comment]
Hi @hay-kot , this issue consider won't fix, correct? Since there is no schema available on this website. The only fixes on this issue will be show [] in the last_recipe.json.

**Comment by hay-kot** [comment]
> Hi @hay-kot , this issue consider won't fix, correct? Since there is no schema available on this website. The only fixes on this issue will be show [] in the last_recipe.json.

Correct. Ideally there would be some plugin architecture to support websites that don't adhere to the schema, but I'm not sure how else to support that besides the existing API.

**Comment by hay-kot** [comment]
Closing this one. If you're interested in supporting additional sites, we now use the https://github.com/hhursev/recipe-scrapers/ library. They have a process for adding new sites which will then be picked up in in Mealie.
