### ISSUE TITLE
JSON exception trying to import recipe from greatbritishchefs.com

### ISSUE THREAD

**Issue by nevado** [hay-kot/mealie#200]
**Describe the bug**
JSON exception trying to import recipe from greatbritishchefs.com

**Steps To Reproduce**
1. Import recipe from URL -> https://www.greatbritishchefs.com/recipes/jam-roly-poly-recipe

**Actual Behavior**
Exception from logs:

```
mealie              | 07-Mar-21 08:00:53 ERROR: Exception in ASGI application
mealie              | Traceback (most recent call last):
mealie              |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
mealie              |     result = await app(self.scope, self.receive, self.send)
mealie              |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
mealie              |     return await self.app(scope, receive, send)
mealie              |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
mealie              |     await super().__call__(scope, receive, send)
mealie              |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
mealie              |     await self.middleware_stack(scope, receive, send)
mealie              |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
mealie              |     raise exc from None
mealie              |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
mealie              |     await self.app(scope, receive, _send)
mealie              |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
mealie              |     raise exc from None
mealie              |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
mealie              |     await self.app(scope, receive, sender)
mealie              |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
mealie              |     await route.handle(scope, receive, send)
mealie              |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
mealie              |     await self.app(scope, receive, send)
mealie              |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
mealie              |     response = await func(request)
mealie              |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
mealie              |     raw_response = await run_endpoint_function(
mealie              |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
mealie              |     return await run_in_threadpool(dependant.call, **values)
mealie              |   File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
mealie              |     return await loop.run_in_executor(None, func, *args)
mealie              |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
mealie              |     result = self.fn(*self.args, **self.kwargs)
mealie              |   File "./routes/recipe/recipe_crud_routes.py", line 30, in parse_recipe_url
mealie              |     recipe = create_from_url(url.url)
mealie              |   File "./services/scraper/scraper.py", line 27, in create_from_url
mealie              |     new_recipe = extract_recipe_from_html(r.text, url)
mealie              |   File "./services/scraper/scraper.py", line 49, in extract_recipe_from_html
mealie              |     scraped_recipes: List[dict] = scrape_schema_recipe.loads(html)
mealie              |   File "/usr/local/lib/python3.9/site-packages/scrape_schema_recipe/scrape.py", line 242, in loads
mealie              |     data = extruct.extract(string)
mealie              |   File "/usr/local/lib/python3.9/site-packages/extruct/_extruct.py", line 108, in extract
mealie              |     output[syntax] = list(extract(document, base_url=base_url))
mealie              |   File "/usr/local/lib/python3.9/site-packages/extruct/jsonld.py", line 25, in extract_items
mealie              |     return [
mealie              |   File "/usr/local/lib/python3.9/site-packages/extruct/jsonld.py", line 25, in <listcomp>
mealie              |     return [
mealie              |   File "/usr/local/lib/python3.9/site-packages/extruct/jsonld.py", line 38, in _extract_items
mealie              |     data = jstyleson.loads(HTML_OR_JS_COMMENTLINE.sub('', script),strict=False)
mealie              |   File "/usr/local/lib/python3.9/site-packages/jstyleson.py", line 123, in loads
mealie              |     return json.loads(dispose(text), **kwargs)
mealie              |   File "/usr/local/lib/python3.9/json/__init__.py", line 359, in loads
mealie              |     return cls(**kw).decode(s)
mealie              |   File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
mealie              |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
mealie              |   File "/usr/local/lib/python3.9/json/decoder.py", line 353, in raw_decode
mealie              |     obj, end = self.scan_once(s, idx)
mealie              | json.decoder.JSONDecodeError: Expecting ':' delimiter: line 6 column 24 (char 122)
```

**Device Information (please complete the following information):**
 - Deployment: docker
 - Version: 0.3.0

**Comment by sephrat** [comment]
This one is weird. Mealie looks for a json structure, and it finds one that has a syntax error, even though it is not relevant to the recipe.
`json.decoder.JSONDecodeError: Expecting ':' delimiter: line 6 column 24 (char 122)` 

```
<script type="application/ld+json">
    {
    "@context": "https://schema.org",
    "@type": "VideoObject",
    "name": "Title",
    "description=video",
    "thumbnailUrl=https://gbc-cdn-public-media.azureedge.net/img66815.1426x802.jpg",
    "contentUrl=https://gbcstoragems1.blob.core.windows.net/asset-a792fa6a-50ae-4ae8-b0d3-3ce5bda56cdb/Jam Roly Poly A2 v4 _960x540_2250.mp4?sv=2015-07-08&amp;sr=c&amp;si=ed36449a-218f-4abd-9334-00a6dbb3ae95&amp;sig=kDAPgaDQZ3P5f4H%2BSwLNtqb%2BwanHjw%2FMgnBODL4dZyI%3D&amp;se=2117-04-10T11:19:16Z",
    "uploadDate=2015-07-03"
    }
</script>
```
It starts great but starting from description, it's messing up with the json format.

I believe in this case we shouldn't even bother with this json structure and we should fallback to html parsing. Not sure if babysitting this edge-case is really the correct approach though.
