### ISSUE TITLE
Not actually python3.8 compatible, hard to run without Docker

### ISSUE THREAD

**Issue by Artanicus** [hay-kot/mealie#211]
Issue occurs both on current master & dev branches but slightly differently.

```
%> python3 -V                    
Python 3.8.5
```

master:
```
mealie.git/mealie %> sudo poetry run ./run.sh
2021/03/20 10:25:54.887 INFO    using provided configuration    {"config_file": "./Caddyfile", "config_adapter": ""}
run: loading initial config: loading new config: starting caddy administration endpoint: listen tcp 127.0.0.1:2019: bind: address already in use
start: caddy process exited with error: exit status 1
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mealie-_3YfsgnH-py3.8/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/root/.cache/pypoetry/virtualenvs/mealie-_3YfsgnH-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/mealie-_3YfsgnH-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/mealie-_3YfsgnH-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.cache/pypoetry/virtualenvs/mealie-_3YfsgnH-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/mealie-_3YfsgnH-py3.8/lib/python3.8/site-packages/uvicorn/main.py", line 362, in main
    run(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/mealie-_3YfsgnH-py3.8/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/mealie-_3YfsgnH-py3.8/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/root/.cache/pypoetry/virtualenvs/mealie-_3YfsgnH-py3.8/lib/python3.8/site-packages/uvicorn/server.py", line 55, in serve
    config.load()
  File "/root/.cache/pypoetry/virtualenvs/mealie-_3YfsgnH-py3.8/lib/python3.8/site-packages/uvicorn/config.py", line 308, in load
    self.loaded_app = import_from_string(self.app)
  File "/root/.cache/pypoetry/virtualenvs/mealie-_3YfsgnH-py3.8/lib/python3.8/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./app.py", line 6, in <module>
    from routes import (
  File "./routes/setting_routes.py", line 4, in <module>
    from models.settings_models import SiteSettings
  File "./models/settings_models.py", line 12, in <module>
    class SiteSettings(BaseModel):
  File "./models/settings_models.py", line 14, in SiteSettings
    planCategories: list[str] = []
TypeError: 'type' object is not subscriptable
```

dev:
```
mealie.git/mealie %> sudo poetry run ./run.sh
2021/03/20 10:34:42.717 INFO    using provided configuration    {"config_file": "./Caddyfile", "config_adapter": ""}
run: loading initial config: loading new config: starting caddy administration endpoint: listen tcp 127.0.0.1:2019: bind: address already in use
start: caddy process exited with error: exit status 1
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mealie-_3YfsgnH-py3.8/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/root/.cache/pypoetry/virtualenvs/mealie-_3YfsgnH-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/mealie-_3YfsgnH-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/mealie-_3YfsgnH-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.cache/pypoetry/virtualenvs/mealie-_3YfsgnH-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/mealie-_3YfsgnH-py3.8/lib/python3.8/site-packages/uvicorn/main.py", line 362, in main
    run(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/mealie-_3YfsgnH-py3.8/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/mealie-_3YfsgnH-py3.8/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/root/.cache/pypoetry/virtualenvs/mealie-_3YfsgnH-py3.8/lib/python3.8/site-packages/uvicorn/server.py", line 55, in serve
    config.load()
  File "/root/.cache/pypoetry/virtualenvs/mealie-_3YfsgnH-py3.8/lib/python3.8/site-packages/uvicorn/config.py", line 308, in load
    self.loaded_app = import_from_string(self.app)
  File "/root/.cache/pypoetry/virtualenvs/mealie-_3YfsgnH-py3.8/lib/python3.8/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./app.py", line 7, in <module>
    from db.db_setup import sql_exists
  File "./db/db_setup.py", line 10, in <module>
    SessionLocal = sql_global_init(SQLITE_FILE)
  File "./db/models/db_session.py", line 21, in sql_global_init
    import db.models._all_models
  File "./db/models/_all_models.py", line 2, in <module>
    from db.models.recipe.recipe import *
  File "./db/models/recipe/recipe.py", line 20, in <module>
    class RecipeModel(SqlAlchemyBase, BaseMixins):
  File "./db/models/recipe/recipe.py", line 85, in RecipeModel
    tool: list[str] = [],
TypeError: 'type' object is not subscriptable
```

Attempting to run without Docker so fully aware that it's probably my fault  but still seems like a bug to me.

**Comment by Artanicus** [comment]
After reinstalling the entire toolchain to be Python 3.9 this issue does not occur. Thus I believe your master branch `python = "^3.8"` is infact a lie. :-)

**Comment by hay-kot** [comment]
It is in-fact a lie. the `list[str]` type annotation is not supported in python 3.8 without importing `__future__`.  Frankly the python package management in the project is embarrassingly bad. It needs some TLC to make mealie into a proper package, fix the hacky imports, and migrate pytest config to the pyproject.toml file.

**Comment by hay-kot** [comment]
To my surprise, fixing all of this stuff was pretty easy. PR #213 should fix everything plus add a makefile to make setting up the dev environment a little easier.

**Comment by Artanicus** [comment]
Nice stuff, already makes a lot of the steps I had to decode from the Dockerfile easier!

A few notes;
- Makefiles usually have a capital M, but that is just a convention, this works as well.
- It depends on platform and how Poetry is configured where the venv ends up, so `./.venv/` assumes things that may not hold true, and for me don't hold true.
- `source` is a bash & zsh shell builtin and cannot be used in a Makefile since it uses sh. You could use the syntax `. ./.venv/bin/activate` but as said, the location isn't static so it won't work anyway.
- To solve both above, you could use `poetry run python mealie/app.py` and so on.

I'll tweak the makefile and do a PR once I get it operational. :-)

**Comment by hay-kot** [comment]
I believe all your comments are addressed in this [commit](https://github.com/hay-kot/mealie/pull/233/commits/535dc7367014c47f8d5694ea7d393f19fa65aece)

If so, can I close this issue once it's merged?
