### ISSUE TITLE
Internal Server Error when adding a new recipe with an existing name

### ISSUE THREAD

**Issue by ltctceplrm** [hay-kot/mealie#212]
**Describe the bug**
It's not really a bug but more of a lack of clear error message, when you add a recipe that has the same name as a recipe already in your database then it gives an Internal Server Error but doesn't tell you why. It took me longer than I'd admit to figure out that I already added a recipe with the same name, I kept retrying to add it and not getting why it wouldn't work.

**Steps To Reproduce**
1. Add a recipe with the same name as an existing recipe
2. Fail to add the recipe and get an Internal Server Error.

**Expected behavior**
Either an error message saying you already have a recipe with the same name, allowing you to change the name of the recipe you're editing without having to re-add everything.
Or adding "(2)" or something like that to the name so it becomes unique.

**Actual Behavior**
Internal Server Error, losing the recipe you were editing.

**Device Information (please complete the following information):**
 - OS: [Debian Buster]
 - Deployment: [docker-compose]
 - Browser: [Firefox]
 - Version: [e.g., 0.3.0]

**Logs**
`````
INFO:     192.168.1.12:0 - "POST /api/recipes/create HTTP/1.1" 500 Internal Ser                                                                                                                                           ver Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_                                                                                                                                           impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.                                                                                                                                           py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 19                                                                                                                                           9, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line                                                                                                                                            111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py",                                                                                                                                            line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py",                                                                                                                                            line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82                                                                                                                                           , in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71                                                                                                                                           , in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566,                                                                                                                                            in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227,                                                                                                                                            in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, i                                                                                                                                           n app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in                                                                                                                                            app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in                                                                                                                                            run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 3                                                                                                                                           4, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./routes/recipe/recipe_crud_routes.py", line 21, in create_from_json
    new_recipe_slug = data.save_to_db(db)
  File "./services/recipe_services.py", line 100, in save_to_db
    recipe_doc = db.recipes.create(session, recipe_dict)
  File "./db/db_base.py", line 128, in create
    session.commit()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line                                                                                                                                            1046, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line                                                                                                                                            504, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line                                                                                                                                            483, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line                                                                                                                                            2540, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line                                                                                                                                            2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py",                                                                                                                                            line 68, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line                                                                                                                                            182, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line                                                                                                                                            2642, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", li                                                                                                                                           ne 422, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", li                                                                                                                                           ne 586, in execute
    persistence.save_obj(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", l                                                                                                                                           ine 239, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", l                                                                                                                                           ine 1135, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line                                                                                                                                            1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line                                                                                                                                            298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line                                                                                                                                            1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line                                                                                                                                            1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line                                                                                                                                            1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line                                                                                                                                            182, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line                                                                                                                                            1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", li                                                                                                                                           ne 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed                                                                                                                                           : recipes.slug
[SQL: INSERT INTO recipes (name, description, image, "recipeYield", "totalTime",                                                                                                                                            "prepTime", "performTime", slug, "dateAdded", rating, "orgURL") VALUES (?, ?, ?                                                                                                                                           , ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('Tarte tatin végane', '', 'tarte-tatin-vegane', '', None, None, No                                                                                                                                           ne, 'tarte-tatin-vegane', '2021-03-20', 0, '')]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
20-Mar-21 11:19:13 ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_                                                                                                                                           impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.                                                                                                                                           py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 19                                                                                                                                           9, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line                                                                                                                                            111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py",                                                                                                                                            line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py",                                                                                                                                            line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82                                                                                                                                           , in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71                                                                                                                                           , in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566,                                                                                                                                            in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227,                                                                                                                                            in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, i                                                                                                                                           n app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in                                                                                                                                            app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in                                                                                                                                            run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 3                                                                                                                                           4, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./routes/recipe/recipe_crud_routes.py", line 21, in create_from_json
    new_recipe_slug = data.save_to_db(db)
  File "./services/recipe_services.py", line 100, in save_to_db
    recipe_doc = db.recipes.create(session, recipe_dict)
  File "./db/db_base.py", line 128, in create
    session.commit()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line                                                                                                                                            1046, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line                                                                                                                                            504, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line                                                                                                                                            483, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line                                                                                                                                            2540, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line                                                                                                                                            2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py",                                                                                                                                            line 68, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line                                                                                                                                            182, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line                                                                                                                                            2642, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", li                                                                                                                                           ne 422, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", li                                                                                                                                           ne 586, in execute
    persistence.save_obj(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", l                                                                                                                                           ine 239, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", l                                                                                                                                           ine 1135, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line                                                                                                                                            1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line                                                                                                                                            298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line                                                                                                                                            1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line                                                                                                                                            1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line                                                                                                                                            1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line                                                                                                                                            182, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line                                                                                                                                            1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", li                                                                                                                                           ne 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed                                                                                                                                           : recipes.slug
[SQL: INSERT INTO recipes (name, description, image, "recipeYield", "totalTime",                                                                                                                                            "prepTime", "performTime", slug, "dateAdded", rating, "orgURL") VALUES (?, ?, ?                                                                                                                                           , ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('Tarte tatin végane', '', 'tarte-tatin-vegane', '', None, None, No                                                                                                                                           ne, 'tarte-tatin-vegane', '2021-03-20', 0, '')]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
INFO:     192.168.1.12:0 - "GET /api/recipes/Internal%20Server%20Error HTTP/1.1                                                                                                                                           " 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_                                                                                                                                           impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.                                                                                                                                           py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 19                                                                                                                                           9, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line                                                                                                                                            111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py",                                                                                                                                            line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py",                                                                                                                                            line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82                                                                                                                                           , in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71                                                                                                                                           , in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566,                                                                                                                                            in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227,                                                                                                                                            in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, i                                                                                                                                           n app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in                                                                                                                                            app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in                                                                                                                                            run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 3                                                                                                                                           4, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./routes/recipe/recipe_crud_routes.py", line 40, in get_recipe
    recipe = Recipe.get_by_slug(db, recipe_slug)
  File "./services/recipe_services.py", line 87, in get_by_slug
    document = db.recipes.get(session, slug, "slug")
  File "./db/db_base.py", line 111, in get
    return db_entries[0]
IndexError: list index out of range
20-Mar-21 11:19:14 ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_                                                                                                                                           impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.                                                                                                                                           py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 19                                                                                                                                           9, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line                                                                                                                                            111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py",                                                                                                                                            line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py",                                                                                                                                            line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82                                                                                                                                           , in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71                                                                                                                                           , in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566,                                                                                                                                            in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227,                                                                                                                                            in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, i                                                                                                                                           n app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in                                                                                                                                            app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in                                                                                                                                            run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 3                                                                                                                                           4, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./routes/recipe/recipe_crud_routes.py", line 40, in get_recipe
    recipe = Recipe.get_by_slug(db, recipe_slug)
  File "./services/recipe_services.py", line 87, in get_by_slug
    document = db.recipes.get(session, slug, "slug")
  File "./db/db_base.py", line 111, in get
    return db_entries[0]

```

**Comment by AnthonyHeide** [comment]
I think it might be best to allow multiple recipes with the same name, since there are often multiple variations on a recipe you might want to try. I'm not sure how you'd prefer to do it, but maybe add an ID field in the database for each recipe?

**Comment by hay-kot** [comment]
> I think it might be best to allow multiple recipes with the same name, since there are often multiple variations on a recipe you might want to try. I'm not sure how you'd prefer to do it, but maybe add an ID field in the database for each recipe?

There is already an id field in the database, but it doesn't really do anything at the moment. The main reason for requiring a unique name is that the whole URL scheme is built around recipe slugs. If you have two recipes that share slug, it would just return the first entry in the database it finds.

An alternative may be to just automatically add an increment of some sort to a recipe with a duplicate name.

**Comment by sephrat** [comment]
A word of caution to the one who will implement supporting recipes with the same name: 
We need to make sure this doesn't break the backup process, which uses the recipe name to create files.

**Comment by ltctceplrm** [comment]
I do indeed think the safest option would to keep unique names and have an auto increment if you try to save a recipe with a name that already exists, otherwise if you have several identically named recipes it might get difficult to find the correct recipes using the search.

**Comment by hay-kot** [comment]
> I do indeed think the safest option would to keep unique names and have an auto increment if you try to save a recipe with a name that already exists, otherwise if you have several identically named recipes it might get difficult to find the correct recipes using the search.

This is the approach I'd like to see. There's too much infrastructure that depends on unique naming...that's not a bear I want to poke!

**Comment by nunofgs** [comment]
I think I hit this issue. Here are steps to reproduce:

1. Add a recipe by url.
2. The recipe gets parsed correctly, but now you forget to save it and go back to the mealie dashboard. 
3. Paste the same url: 500 error.

I’m now stuck and unable to add this recipe at all.

**Comment by Rai-Rai** [comment]
Similar to the issue reported here, I also got 500 messages when renaming a recipe that was already there some time ago.
It looks like the /recipes folder is also not cleaned when a recipe got renamed/deleted, it now looks like that:
![image](https://user-images.githubusercontent.com/2023869/146684216-b04ae77b-06d0-460d-92a7-e48691c56de0.png)
in this example the recipe is now called "Kirschkompottt" sice we only want to keep that part of the imported recipe (the ttt at the end is intentionally since renaming it to "Kirschkompott" doesn't work...

**Comment by ados8** [comment]
+1 very much for matching names.
It's really impractical to tell all my family members (some very tech challenged) to search the library for what increment next.
I think having the system automatically append 1, 2, 3 as needed is good enough.
In regards to tracking instead of IDs can we no use the URL which shouldn't be used more than once per recipe?
