### ISSUE TITLE
403 forbidden error during import - Return Better Errors on Scrape Failure

### ISSUE THREAD

**Issue by dshokouhi** [hay-kot/mealie#456]
**Describe the bug**

While trying to import https://cookpad.com/us/recipes/5544853-sous-vide-smoked-beef-ribs I get a 403 forbidden error in the logs, other sites work fine

**Steps To Reproduce**
Please be specific!
1. Open Mealie
2. Click on import URL
3. Paste URL
4. Observe error

**Sample Code**

**Expected behavior**

It should import properly

**Actual Behavior**

following error is observed in docker logs:

```
403 Client Error: Forbidden for url: https://cookpad.com/us/recipes/5544853-sous-vide-smoked-beef-ribs
INFO:     192.168.1.224:0 - "POST /api/recipes/create-url HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./mealie/routes/recipe/recipe_crud_routes.py", line 42, in parse_recipe_url
    recipe = create_from_url(url.url)
  File "./mealie/services/scraper/scraper.py", line 29, in create_from_url
    new_recipe = extract_recipe_from_html(r.text, url)
  File "./mealie/services/scraper/scraper.py", line 49, in extract_recipe_from_html
    scraped_recipes: List[dict] = scrape_schema_recipe.scrape_url(url)
  File "/usr/local/lib/python3.9/site-packages/scrape_schema_recipe/scrape.py", line 309, in scrape_url
    r.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://cookpad.com/us/recipes/5544853-sous-vide-smoked-beef-ribs
ERROR:  Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./mealie/routes/recipe/recipe_crud_routes.py", line 42, in parse_recipe_url
    recipe = create_from_url(url.url)
  File "./mealie/services/scraper/scraper.py", line 29, in create_from_url
    new_recipe = extract_recipe_from_html(r.text, url)
  File "./mealie/services/scraper/scraper.py", line 49, in extract_recipe_from_html
    scraped_recipes: List[dict] = scrape_schema_recipe.scrape_url(url)
  File "/usr/local/lib/python3.9/site-packages/scrape_schema_recipe/scrape.py", line 309, in scrape_url
    r.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://cookpad.com/us/recipes/5544853-sous-vide-smoked-beef-ribs

```

**Screenshots**

**Device Information (please complete the following information):**
 - OS: raspberry OS
 - Deployment: Docker using example from installation
 - Browser: chrome
 - Version: 0.4.3

**Additional context**

**Comment by hay-kot** [comment]
If you curl the website you get a very nice message

> Access to this page has been denied because we believe you are using automation tools to browse the website. </p> <p> This may happen as a result of the following: </p> <ul> <li> Javascript is disabled or blocked by an extension (ad blockers for example) </li> <li> Your browser does not support cookies </li> </ul> <p> Please make sure that Javascript and cookies are enabled on your browser and that you are not blocking them from loading.

I think circumventing blocks like this is outside of something I'd want to support in the project. I'm afraid you'll have to manually copy/paste any recipes from their site.

**Comment by dshokouhi** [comment]
Not a problem at all.....should I close this issue or should we keep this open to update an error message telling users they need to import sites like this manually? I ask because I figure it might help the next person who hits the same 403 error.

The copy/paste is super simple too.

**Comment by hay-kot** [comment]
> Not a problem at all.....should I close this issue or should we keep this open to update an error message telling users they need to import sites like this manually? I ask because I figure it might help the next person who hits the same 403 error.

Let's keep it open for now. I'll use it at a jumping off point for improving the error handling/user interaction when scraping. Thanks! 👍

**Comment by hay-kot** [comment]
The new recipe parser library I'm using seems to resolve this issue. I was able to get the recipe in the demo-site/beta. 

https://mealie-demo.hay-kot.dev/recipe/sous-vide-smoked-beef-ribs
