### ISSUE TITLE
Failed to import Backup after update from 0.4.3 to 0.5.1

### ISSUE THREAD

**Issue by justsomebody42** [hay-kot/mealie#552]
**Describe the bug**
Internal server error, when importing the backup made with v0.4.3 after update to 0.5.1

**Steps To Reproduce**
1. Create Backup with version 0.4.3
2. Update to version 0.5.1
3. Import Backup

**Expected behavior**
All data present as before

**Actual Behavior**
Internal server error during import. Only a few recipies are imported, no users or anything else.
Import probably crashed

Exception:
```
OSError: [Errno 18] Invalid cross-device link: '/app/data/img/downtown-marinade' -> '/app/data/recipes/downtown-marinade/images'
ERROR: 17-Jun-21 22:03:39 	Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/./mealie/routes/backup_routes.py", line 89, in import_database
    db_import = imports.import_database(
  File "/app/./mealie/services/backups/imports.py", line 362, in import_database
    recipe_report = import_session.import_recipes()
  File "/app/./mealie/services/backups/imports.py", line 85, in import_recipes
    self._import_images(successful_imports)
  File "/app/./mealie/services/backups/imports.py", line 157, in _import_images
    minify.migrate_images()
  File "/app/./mealie/services/image/minify.py", line 118, in migrate_images
    move_all_images()
  File "/app/./mealie/services/image/minify.py", line 112, in move_all_images
    image_file.rename(Recipe(slug=slug).image_dir)
  File "/usr/local/lib/python3.9/pathlib.py", line 1372, in rename
    self._accessor.rename(self, target)
OSError: [Errno 18] Invalid cross-device link: '/app/data/img/downtown-marinade' -> '/app/data/recipes/downtown-marinade/images'
```

**Comment by hay-kot** [comment]
```
OSError: [Errno 18] Invalid cross-device link: '/app/data/img/downtown-marinade' -> '/app/data/recipes/downtown-marinade/images'
```

Seems to indicate that the two files paths on on different file systems. No clue what would cause that. Can you post your docker-compose / run command?

**Comment by mitchelloharawild** [comment]
I also had this issue. The issue for me was that the container's volume configuration was based on a much older version (v0.1.0 in my case - thanks for the great project!)

Updating
```
    volumes:
      - ~/mealie/data/img:/app/data/img
      - ~/mealie/data/backups:/app/data/backups
```
to
```
    volumes:
      - ~/mealie/data/:/app/data
```

as described in https://hay-kot.github.io/mealie/documentation/getting-started/install/ resolved the issue.

**Comment by picto3000** [comment]
I have the same issue.

- Loading my 0.4.3 backup with all data types selected gives me a similar error, and the only thing that comes across are recipes and no associated images. User, settings etc. are not imported. So the import appears to error and stop.
- Unticking recipes and importing all other data types completes successfully.
- I only have the /app/data folder in Docker Compose.

```
  mealie:
    container_name: mealie
    image: hkotel/mealie
    environment:
      DB_TYPE: sqlite
      TOKEN_TIME: 672
    ports:
      - 9099:80
    volumes:
      - ${USERDIR}/docker/mealie/data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mealie-rtr.entrypoints=https"
      - "traefik.http.routers.mealie-rtr.rule=Host(`meals.$DOMAINNAME`)"
      - "traefik.http.routers.mealie-rtr.tls=true"
      - "traefik.http.routers.mealie-rtr.middlewares=chain-oauth@file" # Google OAuth 2.0
      - "traefik.http.routers.mealie-rtr.service=mealie-svc"
      - "traefik.http.services.mealie-svc.loadbalancer.server.port=80" 
    << : *baseline
```

```
today at 2:49:45 PM INFO: 18-Jun-21 04:49:45 	Checking for Images to Minify...
today at 2:49:45 PM INFO:     172.19.0.13:0 - "POST /api/backups/Preemptive%20v0.05%20backup_2021-Jun-17.zip/import HTTP/1.1" 500 Internal Server Error
today at 2:49:45 PM ERROR:    Exception in ASGI application
today at 2:49:45 PM Traceback (most recent call last):
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
today at 2:49:45 PM     result = await app(self.scope, self.receive, self.send)
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
today at 2:49:45 PM     return await self.app(scope, receive, send)
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
today at 2:49:45 PM     await super().__call__(scope, receive, send)
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
today at 2:49:45 PM     await self.middleware_stack(scope, receive, send)
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
today at 2:49:45 PM     raise exc from None
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
today at 2:49:45 PM     await self.app(scope, receive, _send)
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
today at 2:49:45 PM     raise exc from None
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
today at 2:49:45 PM     await self.app(scope, receive, sender)
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
today at 2:49:45 PM     await route.handle(scope, receive, send)
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
today at 2:49:45 PM     await self.app(scope, receive, send)
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
today at 2:49:45 PM     response = await func(request)
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
today at 2:49:45 PM     raw_response = await run_endpoint_function(
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
today at 2:49:45 PM     return await run_in_threadpool(dependant.call, **values)
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
today at 2:49:45 PM     return await loop.run_in_executor(None, func, *args)
today at 2:49:45 PM   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
today at 2:49:45 PM     result = self.fn(*self.args, **self.kwargs)
today at 2:49:45 PM   File "/app/./mealie/routes/backup_routes.py", line 89, in import_database
today at 2:49:45 PM     db_import = imports.import_database(
today at 2:49:45 PM   File "/app/./mealie/services/backups/imports.py", line 362, in import_database
today at 2:49:45 PM     recipe_report = import_session.import_recipes()
today at 2:49:45 PM   File "/app/./mealie/services/backups/imports.py", line 85, in import_recipes
today at 2:49:45 PM     self._import_images(successful_imports)
today at 2:49:45 PM   File "/app/./mealie/services/backups/imports.py", line 157, in _import_images
today at 2:49:45 PM     minify.migrate_images()
today at 2:49:45 PM   File "/app/./mealie/services/image/minify.py", line 118, in migrate_images
today at 2:49:45 PM     move_all_images()
today at 2:49:45 PM   File "/app/./mealie/services/image/minify.py", line 112, in move_all_images
today at 2:49:45 PM     image_file.rename(Recipe(slug=slug).image_dir)
today at 2:49:45 PM   File "/usr/local/lib/python3.9/pathlib.py", line 1372, in rename
today at 2:49:45 PM     self._accessor.rename(self, target)
today at 2:49:45 PM OSError: [Errno 39] Directory not empty: '/app/data/img/sheet-pan-gnocchi' -> '/app/data/recipes/sheet-pan-gnocchi/images'
today at 2:49:45 PM ERROR: 18-Jun-21 04:49:45 	Exception in ASGI application
today at 2:49:45 PM Traceback (most recent call last):
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
today at 2:49:45 PM     result = await app(self.scope, self.receive, self.send)
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
today at 2:49:45 PM     return await self.app(scope, receive, send)
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
today at 2:49:45 PM     await super().__call__(scope, receive, send)
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
today at 2:49:45 PM     await self.middleware_stack(scope, receive, send)
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
today at 2:49:45 PM     raise exc from None
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
today at 2:49:45 PM     await self.app(scope, receive, _send)
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
today at 2:49:45 PM     raise exc from None
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
today at 2:49:45 PM     await self.app(scope, receive, sender)
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
today at 2:49:45 PM     await route.handle(scope, receive, send)
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
today at 2:49:45 PM     await self.app(scope, receive, send)
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
today at 2:49:45 PM     response = await func(request)
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
today at 2:49:45 PM     raw_response = await run_endpoint_function(
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
today at 2:49:45 PM     return await run_in_threadpool(dependant.call, **values)
today at 2:49:45 PM   File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
today at 2:49:45 PM     return await loop.run_in_executor(None, func, *args)
today at 2:49:45 PM   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
today at 2:49:45 PM     result = self.fn(*self.args, **self.kwargs)
today at 2:49:45 PM   File "/app/./mealie/routes/backup_routes.py", line 89, in import_database
today at 2:49:45 PM     db_import = imports.import_database(
today at 2:49:45 PM   File "/app/./mealie/services/backups/imports.py", line 362, in import_database
today at 2:49:45 PM     recipe_report = import_session.import_recipes()
today at 2:49:45 PM   File "/app/./mealie/services/backups/imports.py", line 85, in import_recipes
today at 2:49:45 PM     self._import_images(successful_imports)
today at 2:49:45 PM   File "/app/./mealie/services/backups/imports.py", line 157, in _import_images
today at 2:49:45 PM     minify.migrate_images()
today at 2:49:45 PM   File "/app/./mealie/services/image/minify.py", line 118, in migrate_images
today at 2:49:45 PM     move_all_images()
today at 2:49:45 PM   File "/app/./mealie/services/image/minify.py", line 112, in move_all_images
today at 2:49:45 PM     image_file.rename(Recipe(slug=slug).image_dir)
today at 2:49:45 PM   File "/usr/local/lib/python3.9/pathlib.py", line 1372, in rename
today at 2:49:45 PM     self._accessor.rename(self, target)
today at 2:49:45 PM OSError: [Errno 39] Directory not empty: '/app/data/img/sheet-pan-gnocchi' -> '/app/data/recipes/sheet-pan-gnocchi/images'
today at 2:49:46 PM INFO:     172.19.0.13:0 - "GET /api/recipes/summary HTTP/1.1" 200 OK
today at 2:49:47 PM INFO:     172.19.0.13:0 - "GET /api/recipes/summary HTTP/1.1" 200 OK
```

**Comment by justsomebody42** [comment]
This worked like a charm!
Thanks a lot for pointing out.
I didn't catch this in any update note. I shall read more carefully ;)
Thanks!
