### ISSUE TITLE
Dev Branch Broken Gunicorn

### ISSUE THREAD

**Issue by zierbeek** [hay-kot/mealie#606]
**Describe the bug**
Updating to latest dev build of July 1st breaks mealie totally. Failing to boot

**Sample Code**
Docker compose: 
```yaml
mealie:
    container_name: mealie
    image: hkotel/mealie:dev
    restart: always
    ports:
      - 9925:80
    environment:
      TZ: Europe/Brussels
      PUID: 1000
      PGID: 1000
      # WORKERS_PER_CORE: 0.5
      # MAX_WORKERS: 8
      WEB_CONCURRENCY: 2
    volumes:
      - ./mealie/data/:/app/data
```
      
Logs: 
```Production
usermod: no changes

    User uid:    1000
    User gid:    1000
    
Database Exists
INFO: 02-Jul-21 00:00:42 	Checking for Images to Minify...
INFO: 02-Jul-21 00:00:42 	Finished Minification Check
{"level":"info","ts":1625176842.6764698,"msg":"using provided configuration","config_file":"/app/Caddyfile","config_adapter":""}
{"level":"warn","ts":1625176842.6777897,"msg":"input is not formatted with 'caddy fmt'","adapter":"caddyfile","file":"/app/Caddyfile","line":3}
{"level":"warn","ts":1625176842.6781805,"logger":"admin","msg":"admin endpoint disabled"}
{"level":"info","ts":1625176842.6784554,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0002d1730"}
{"level":"info","ts":1625176842.6791785,"msg":"autosaved config (load with --resume flag)","file":"/root/.config/caddy/autosave.json"}
{"level":"info","ts":1625176842.6791787,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/root/.local/share/caddy"}
{"level":"info","ts":1625176842.6792927,"msg":"serving initial configuration"}
{"level":"info","ts":1625176842.679347,"logger":"tls","msg":"finished cleaning storage units"}
Successfully started Caddy (pid=29) - Caddy is running in the background
{"loglevel": "info", "workers": 2, "bind": "127.0.0.1:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": null, "host": "127.0.0.1", "port": "80"}
[2021-07-02 00:00:43 +0200] [37] [INFO] Starting gunicorn 20.1.0
[2021-07-02 00:00:43 +0200] [37] [INFO] Listening at: http://0.0.0.0:9000 (37)
[2021-07-02 00:00:43 +0200] [37] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2021-07-02 00:00:43 +0200] [37] [INFO] Unhandled exception in main loop
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 202, in run
    self.manage_workers()
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 551, in manage_workers
    self.spawn_workers()
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 622, in spawn_workers
    self.spawn_worker()
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 569, in spawn_worker
    worker = self.worker_class(self.worker_age, self.pid, self.LISTENERS,
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/uvicorn/workers.py", line 20, in __init__
    super(UvicornWorker, self).__init__(*args, **kwargs)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 64, in __init__
    self.tmp = WorkerTmp(cfg)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/gunicorn/workers/workertmp.py", line 22, in __init__
    raise RuntimeError("%s doesn't exist. Can't create workertmp." % fdir)
RuntimeError: /mem doesn't exist. Can't create workertmp.
```

**Device Information (please complete the following information):**
 - OS: Linux
 - Deployment:docker-compose
 - Version: 0.5.1-dev

**Comment by hay-kot** [comment]
I can't replicate the issue on the latest build. Can you try pulling again and giving it a go?

**Comment by wengtad** [comment]
It's because the tmpfs I had added in previously, it's removed at #603 , so should be not an issue now.

**Comment by zierbeek** [comment]
> It's because the tmpfs I had added in previously, it's removed at #603 , so should be not an issue now.

But thé docker.compose is correct ?

**Comment by wengtad** [comment]
> > It's because the tmpfs I had added in previously, it's removed at #603 , so should be not an issue now.
> 
> But thé docker.compose is correct ?

Yes, and the PR is merged, so try to pull and go as hay-kot mentioned.

**Comment by zierbeek** [comment]
No idea what fixed it, but it's back alive ;) thanks guys!
