### ISSUE TITLE
API of today's image returns strange characters

### ISSUE THREAD

**Issue by DevSecNinja** [hay-kot/mealie#625]
**Describe the bug**
I'm running the following API call to get the image of today's mealplan:

````
curl -X 'GET' \
  'https://<MY-URL>/api/meal-plans/today/image?group_name=Home' \
  -H 'accept: application/json'
````

Instead of the image, it returns strange characters:

![image](https://user-images.githubusercontent.com/14926452/125208130-0069c880-e291-11eb-96a0-5e2b0a17cf66.png)

**Steps To Reproduce**
Please be specific!
1. Make sure your recipe contains an image. Confirm the image is displayed correctly within the Mealie UI.
2. Run the CURL command mentioned above or open it in your browser.
3. API returns strange characters.

**Sample Code**
See above

**Expected behavior**
The image should be displayed

**Actual Behavior**
Strange characters are returned in both browser and in Swagger.

**Screenshots**
See above

**Device Information (please complete the following information):**
 - OS: Docker on Ubuntu Server
 - Deployment: docker-compose
 - Browser: Microsoft Edge (Chromium)
 - Version: 0.5.1

**Additional context**

(Today I discovered Mealie - what a great way to store recipes! Thanks!)

**Comment by sephrat** [comment]
> Additionally, this should be a public route

I'm not in front of the code, but the meal plan depends on the user group so how can it be a public route without knowing which group to look at?
Also, my take on it was that a family's meal plan is private and should only be accessible to the family.

**Comment by hay-kot** [comment]
> I'm not in front of the code, but the meal plan depends on the user group so how can it be a public route without knowing which group to look at?

This route uses query parameters to get at the group. 

> Also, my take on it was that a family's meal plan is private and should only be accessible to the family.

This route isn't used by any Frontend code, it is just a helper route for accessing the meal-plan image so you can easily embed it in Home Assistant with just the URL and not have to worry about a token. Since all the recipe images are public anyways I don't think it makes a difference here to have this as a public route.

**Comment by DevSecNinja** [comment]
@hay-kot Thanks for fixing it! The only problem is now that it throws an HTTP 500 error message when opening the URL mentioned earlier. Docker logs:

````
192.168.1.10:0 - "GET /api/meal-plans/today/image HTTP/1.1" 500
[2021-08-06 19:09:44 +0200] [40] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/mealie/routes/mealplans/crud.py", line 58, in get_todays_image
    recipe_image = recipe.image_dir.joinpath(image.ImageOptions.ORIGINAL_IMAGE)
AttributeError: 'NoneType' object has no attribute 'image_dir'

````

Any idea what it could be? Thanks!

**Comment by hay-kot** [comment]
> AttributeError: 'NoneType' object has no attribute 'image_dir'

Makes me think that there's no meal planned for the day, but I'm not sure. I just tried it in production and didn't get the same issue, but I did get the text issue again...for some reason????!?!? It definitely worked in development so I'm going to reopen and take another look at what's going on.

**Comment by DevSecNinja** [comment]
Aah that's correct indeed. I added a new meal plan and got indeed the text issue. Maybe it's an idea to throw a different message when no meal plan has been defined? Thanks!
