### ISSUE TITLE
update 0.52 database lock error

### ISSUE THREAD

**Issue by usma0118** [hay-kot/mealie#643]
After latest update to 0.5.2, I am getting database locked error.
have already tried with fresh installation but to no avail.

`[2021-08-01 11:26:24 +0000] [71] [ERROR] Application startup failed. Exiting.
[2021-08-01 11:26:24 +0000] [71] [INFO] Worker exiting (pid: 71)
[2021-08-01 11:26:24 +0000] [70] [ERROR] Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: attempt to write a readonly database

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/routing.py", line 526, in lifespan
    async for item in self.lifespan_context(app):
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/routing.py", line 467, in default_lifespan
    await self.startup()
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/routing.py", line 504, in startup
    handler()
  File "/app/mealie/app.py", line 63, in system_startup
    start_scheduler()
  File "/app/mealie/app.py", line 29, in start_scheduler
    import mealie.services.scheduler.scheduled_jobs  # noqa: F401
  File "/app/mealie/services/scheduler/scheduled_jobs.py", line 121, in <module>
    scheduler.start()
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/apscheduler/schedulers/background.py", line 35, in start
    BaseScheduler.start(self, *args, **kwargs)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 167, in start
    self._real_add_job(job, jobstore_alias, replace_existing)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 872, in _real_add_job
    store.add_job(job)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/apscheduler/jobstores/sqlalchemy.py", line 98, in add_job
    self.engine.execute(insert)
  File "<string>", line 2, in execute
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 390, in warned
    return fn(*args, **kwargs)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3108, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1263, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1452, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1814, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception
    util.raise_(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: INSERT INTO apscheduler_jobs (id, next_run_time, job_state) VALUES (?, ?, ?)]
[parameters: ('396a3a2c1b624037b8c3f1f2ca439b55', 1627903576.331971, <memory at 0x7f848579fd00>)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
`

**Device Information (please complete the following information):**
 - OS: [e.g., WSL2 on Win10, Mac]
 - Deployment: Docker
 - Browser: Chrome

**Additional context**

**Comment by usma0118** [comment]
more details:
```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) disk I/O error
[SQL: 
CREATE TABLE apscheduler_jobs (
	id VARCHAR(191) NOT NULL, 
	next_run_time FLOAT, 
	job_state BLOB NOT NULL, 
	PRIMARY KEY (id)
)

]

```

**Comment by hay-kot** [comment]
APScheduler is a 3rd party scheduling library we use that handles their own SQL Database. Can you remove the `scheduler.db` and try restarting to see if that resolves the issue? It should automatically be recreated.

**Comment by usma0118** [comment]
tried couple of time and than it started working. not sure why.

**Comment by sserenade** [comment]
If possible, I'd like to suggest reopening this issue as it's present on my setup on 0.5.2. This happens even with a fresh container of Mealie with no configuration files. This problem is not present in my setup with 0.5.1, however, so I've rolled back for now.

Mealie's persistent data directory is mounted over NFS in k8s. I've set `PGID` and `PUID` to `1001`, because NFS. This usually allows most containers to work, but I suspect it might be causing problems here with APScheduler, since with 0.5.1, `scheduler.db` isn't in the directory. FWIW, the other containers I have that use sqlite over NFS mounts have no problem reading and writing from .db files, so not too sure if there's anything you might be able to do here.

**Device Information (please complete the following information):**
 - OS: Arch Linux
 - Deployment: Docker version
 - Browser: Firefox
 - Version: 0.5.2

**Comment by hay-kot** [comment]
It's definitely to do with Advanced Python Scheduler. I'm still unsure why this is going, but the reason we added the scheduler.db was because there are now multiple workers so we needed to share scheduler data across instances since they can't all access the same object in memory. 

My gut says you're on the right track and that when APScheduler creates the database with the wrong ID's. Can you verify if all the file permissions is set correctly once the container is running?

**Comment by sserenade** [comment]
I think I've experienced the behavior mentioned earlier, where mealie stops throwing the error.

When the container starts, it logs the error mentioned earlier. It creates, deletes, and recreates `scheduler.db` repeatedly with `644` permissions, which is the same as `mealie_v0.5.0.db`, which it has no issues writing to. When I list the directory, the file is either gone, present but empty, or present with the `apscheduler_jobs` table definition and no other data. I let it run for a while, and it seems, sometimes, it will eventually succeed in creating the database.

```
drwxr-xr-x 2 1001 1001      2 Aug 22 12:12 backups
drwxr-xr-x 2 1001 1001      2 Aug 22 12:12 debug
drwxr-xr-x 2 1001 1001      2 Aug 22 12:12 img
-rw-r--r-- 1 1001 1001 608129 Aug 22 12:20 mealie.log
-rw-r--r-- 1 1001 1001 233472 Aug 22 12:12 mealie_v0.5.0.db
drwxr-xr-x 4 1001 1001      4 Aug 22 12:12 migration
drwxr-xr-x 2 1001 1001      2 Aug 22 12:12 recipes
-rw-r--r-- 1 1001 1001      0 Aug 22 12:20 scheduler.db
-rw-r--r-- 1 1001 1001    512 Aug 22 12:20 scheduler.db-journal
drwxr-xr-x 2 1001 1001      2 Aug 22 12:12 templates
drwxr-xr-x 2 1001 1001      2 Aug 22 12:12 users
```

Other errors thrown during this process are:

```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table apscheduler_jobs already exists
[SQL: 
CREATE TABLE apscheduler_jobs (
	id VARCHAR(191) NOT NULL, 
	next_run_time FLOAT, 
	job_state BLOB NOT NULL, 
	PRIMARY KEY (id)
)
]
```

```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: apscheduler_jobs
[SQL: INSERT INTO apscheduler_jobs (id, next_run_time, job_state) VALUES (?, ?, ?)]
[parameters: ('4369bc6b681447ea9f2af97ab322a778', 1629746224.909531, <memory at 0x7fa8ea993f40>)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2021-08-22 12:17:05 -0700] [9898] [ERROR] Application startup failed. Exiting.
[2021-08-22 12:17:05 -0700] [9898] [INFO] Worker exiting (pid: 9898)
INFO: 22-Aug-21 12:17:05 	Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO: 22-Aug-21 12:17:05 	None
Pending jobs:
    purge_events_database (trigger: interval[1 day, 0:00:00], pending)
    update_webhook_schedule (trigger: interval[0:30:00], pending)
    backups (trigger: cron[hour='0', minute='0'], pending)
    Home (trigger: cron[hour='0', minute='0'], pending)
INFO: 22-Aug-21 12:17:05 	None
```

However, it looks like even when the database is successfully created, there are issues looking up jobs:

```
INFO: 21-Aug-21 21:03:37 	Job "update_webhook_schedule (trigger: interval[0:30:00], next run at: 2021-08-21 21:33:36 PDT)" executed successfully
INFO: 21-Aug-21 21:33:36 	Running job "update_webhook_schedule (trigger: interval[0:30:00], next run at: 2021-08-21 22:03:36 PDT)" (scheduled at 2021-08-21 21:33:36.726573-07:00)
INFO: 21-Aug-21 21:33:36 	Running job "update_webhook_schedule (trigger: interval[0:30:00], next run at: 2021-08-21 22:03:36 PDT)" (scheduled at 2021-08-21 21:33:36.726573-07:00)
INFO: 21-Aug-21 21:33:36 	Running job "update_webhook_schedule (trigger: interval[0:30:00], next run at: 2021-08-21 22:03:36 PDT)" (scheduled at 2021-08-21 21:33:36.726573-07:00)
ERROR: 21-Aug-21 21:33:36 	Job "update_webhook_schedule (trigger: interval[0:30:00], next run at: 2021-08-21 22:03:36 PDT)" raised an exception
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/mealie/services/scheduler/scheduled_jobs.py", line 54, in update_webhook_schedule
    scheduler.reschedule_job(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 516, in reschedule_job
    return self.modify_job(job_id, jobstore, trigger=trigger, next_run_time=next_run_time)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 488, in modify_job
    job, jobstore = self._lookup_job(job_id, jobstore)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 821, in _lookup_job
    raise JobLookupError(job_id)
apscheduler.jobstores.base.JobLookupError: 'No job by the id of a6d7fee2993c4c77a8178fdc9e2a891b was found'
INFO: 21-Aug-21 21:33:36 	Running job "update_webhook_schedule (trigger: interval[0:30:00], next run at: 2021-08-21 22:03:36 PDT)" (scheduled at 2021-08-21 21:33:36.805330-07:00)
ERROR: 21-Aug-21 21:33:36 	Job "update_webhook_schedule (trigger: interval[0:30:00], next run at: 2021-08-21 22:03:36 PDT)" raised an exception
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/mealie/services/scheduler/scheduled_jobs.py", line 54, in update_webhook_schedule
    scheduler.reschedule_job(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 516, in reschedule_job
    return self.modify_job(job_id, jobstore, trigger=trigger, next_run_time=next_run_time)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 488, in modify_job
    job, jobstore = self._lookup_job(job_id, jobstore)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 821, in _lookup_job
    raise JobLookupError(job_id)
apscheduler.jobstores.base.JobLookupError: 'No job by the id of 5e0f53a7a192435085aa19e0802962c5 was found'
Jobstore default:
    update_webhook_schedule (trigger: interval[0:30:00], next run at: 2021-08-21 22:03:36 PDT)
    update_webhook_schedule (trigger: interval[0:30:00], next run at: 2021-08-21 22:03:36 PDT)
    backups (trigger: cron[hour='0', minute='0'], next run at: 2021-08-22 00:00:00 PDT)
    Home (trigger: cron[hour='0', minute='0'], next run at: 2021-08-22 00:00:00 PDT)
    backups (trigger: cron[hour='0', minute='0'], next run at: 2021-08-22 00:00:00 PDT)
    Home (trigger: cron[hour='0', minute='0'], next run at: 2021-08-22 00:00:00 PDT)
    purge_events_database (trigger: interval[1 day, 0:00:00], next run at: 2021-08-22 19:03:36 PDT)
    purge_events_database (trigger: interval[1 day, 0:00:00], next run at: 2021-08-22 19:03:36 PDT)
INFO: 21-Aug-21 21:33:36 	None
INFO: 21-Aug-21 21:33:36 	Job "update_webhook_schedule (trigger: interval[0:30:00], next run at: 2021-08-21 22:03:36 PDT)" executed successfully
```

Perhaps there's a race condition which will result in the database creation eventually succeeding?

**Comment by twsl** [comment]
Same issue, using the unraid template

**Comment by usma0118** [comment]
it seems to be issue with permissions:
-rwxr-xr-x  mealie_v0.5.0.db
-rw-r--r-- scheduler.db
-rw-r--r-- scheduler.db-journal

mealie.db has 755
while scheduler has only 644

I was able to reproduce it while running container as non-root.

**Comment by usma0118** [comment]
stat -c "%a %n" *

`644 backups
755 debug
755 img
644 mealie.log
755 mealie_v0.5.0.db
755 migration
755 recipes
644 scheduler.db
644 scheduler.db-journal
755 templates
755 users
`
