### ISSUE TITLE
Open api spec is not valid

### ISSUE THREAD

**Issue by mat1th** [hay-kot/mealie#665]
**Describe the bug**
Thank you for your nice project!

In your Readme you are that the project is using swagger for API documentation. But the API definition from https://hay-kot.github.io/mealie/api/redoc/ is not valid. There are some definitions missing for URL parameters. 

When you use https://github.com/OpenAPITools/openapi-generator it will also check if the spec is valid. But it gives the following error:
```
-attribute paths.'/api/users/{id}/favorites/{slug}'. Declared path parameter id needs to be defined as a path parameter in path or operation level
-attribute paths.'/api/recipes/{slug}/comments/{id}'. Declared path parameter slug needs to be defined as a path parameter in path or operation level
```

So basically it says it is missing some parameters in the definition. To fix this you need to apply the following patch on the swagger.json file:
```
---
 swagger.json | 36 ++++++++++++++++++++++++++++++++++++
 1 file changed, 36 insertions(+)

diff --git a/swagger.json b/swagger.json
index 96decdd..9ff248b 100644
--- a/swagger.json
+++ b/swagger.json
@@ -703,6 +703,15 @@
         "description": "Adds a Recipe to the users favorites ",
         "operationId": "add_favorite_api_users__id__favorites__slug__post",
         "parameters": [
+           {
+            "required": true,
+            "schema": {
+              "title": "Id",
+              "type": "integer"
+            },
+            "name": "id",
+            "in": "path"
+          },
           {
             "required": true,
             "schema": {
@@ -747,6 +756,15 @@
         "description": "Adds a Recipe to the users favorites ",
         "operationId": "remove_favorite_api_users__id__favorites__slug__delete",
         "parameters": [
+          {
+            "required": true,
+            "schema": {
+              "title": "Id",
+              "type": "integer"
+            },
+            "name": "id",
+            "in": "path"
+          },
           {
             "required": true,
             "schema": {
@@ -2707,6 +2725,15 @@
         "description": "Update comment in the Database ",
         "operationId": "update_comment_api_recipes__slug__comments__id__put",
         "parameters": [
+          {
+            "required": true,
+            "schema": {
+              "title": "Slug",
+              "type": "string"
+            },
+            "name": "slug",
+            "in": "path"
+          },
           {
             "required": true,
             "schema": {
@@ -2761,6 +2788,15 @@
         "description": "Delete comment from the Database ",
         "operationId": "delete_comment_api_recipes__slug__comments__id__delete",
         "parameters": [
+          {
+            "required": true,
+            "schema": {
+              "title": "Slug",
+              "type": "string"
+            },
+            "name": "slug",
+            "in": "path"
+          },
           {
             "required": true,
             "schema": {
-- 
2.31.1

```

**Steps To Reproduce**
1.  Download the `swagger.json` file from https://hay-kot.github.io/mealie/api/redoc/
2. Run `brew install openapi-generator` in the terminal
3. Run `openapi-generator generate -i /<path to>/swagger.json -g typescript -o ./test/`.
4. Now it will give the error.

**Expected behaviour**
It should generate the client side code bases on the swagger.json file.

**Actual Behaviour**
It fails with: 
```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 2, Warning count: 0
Errors:
	-attribute paths.'/api/users/{id}/favorites/{slug}'. Declared path parameter id needs to be defined as a path parameter in path or operation level
	-attribute paths.'/api/recipes/{slug}/comments/{id}'. Declared path parameter slug needs to be defined as a path parameter in path or operation level

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:546)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:573)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:433)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

**Screenshots**

**Device Information (please complete the following information):**
 - OS: WSL2 on Win10, Mac, debian, etc
 - Deployment: none
 - Browser: chrome, safari, firefox
 - Version: 0.5.2

**Comment by hay-kot** [comment]
This should definitely be fixed. Can you submit a test case that will check validation of the API specification in CI?

**Comment by mat1th** [comment]
You could use the json output of https://github.com/hay-kot/mealie/blob/mealie-next/dev/scripts/api_docs_gen.py and lint it with https://github.com/stoplightio/spectral to validate the output.
