### ISSUE TITLE
error when starting

### ISSUE THREAD

**Issue by Jab2870** [hay-kot/mealie#88]
Hi,

I really like the look of mealie although am struggling to get started

I ran the docker command from the instalation instructions:

```
docker run \
    -e db_type='sqlite' \
    -p 9000:80 \
    -v `pwd`:'/app/data/' \
    hkotel/mealie:latest
```

after a while I get the following on stderr

```
Traceback (most recent call last):
  File "./services/settings_services.py", line 49, in get_site_settings
    document = SiteSettingsDocument.objects.get(name="main")
  File "/usr/local/lib/python3.8/site-packages/mongoengine/queryset/manager.py", line 37, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "/usr/local/lib/python3.8/site-packages/mongoengine/document.py", line 207, in _get_collection
    db = cls._get_db()
  File "/usr/local/lib/python3.8/site-packages/mongoengine/document.py", line 185, in _get_db
    return get_db(cls._meta.get("db_alias", DEFAULT_CONNECTION_NAME))
  File "/usr/local/lib/python3.8/site-packages/mongoengine/connection.py", line 367, in get_db
    db.authenticate(
  File "/usr/local/lib/python3.8/site-packages/pymongo/database.py", line 1492, in authenticate
    self.client._cache_credentials(
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 775, in _cache_credentials
    server = self._get_topology().select_server(
  File "/usr/local/lib/python3.8/site-packages/pymongo/topology.py", line 241, in select_server
    return random.choice(self.select_servers(selector,
  File "/usr/local/lib/python3.8/site-packages/pymongo/topology.py", line 199, in select_servers
    server_descriptions = self._select_servers_loop(
  File "/usr/local/lib/python3.8/site-packages/pymongo/topology.py", line 215, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: mongo:27017: [Errno -5] No address associated with hostname, Timeout: 30s, Topology Description: <TopologyDescription id: 60056f33a2d6080b5aec4862, topology_type: Single, servers: [<ServerDescription ('mongo', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo:27017: [Errno -5] No address associated with hostname')>]>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 339, in main
    run(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 362, in run
    server.run()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 397, in serve
    config.load()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/config.py", line 278, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./app.py", line 8, in <module>
    from routes import (
  File "./routes/setting_routes.py", line 13, in <module>
    scheduler.startup_scheduler()
  File "./services/scheduler_services.py", line 43, in startup_scheduler
    settings = SiteSettings.get_site_settings()
  File "./services/settings_services.py", line 53, in get_site_settings
    document.save()
  File "/usr/local/lib/python3.8/site-packages/mongoengine/document.py", line 403, in save
    self.ensure_indexes()
  File "/usr/local/lib/python3.8/site-packages/mongoengine/document.py", line 889, in ensure_indexes
    collection = cls._get_collection()
  File "/usr/local/lib/python3.8/site-packages/mongoengine/document.py", line 207, in _get_collection
    db = cls._get_db()
  File "/usr/local/lib/python3.8/site-packages/mongoengine/document.py", line 185, in _get_db
    return get_db(cls._meta.get("db_alias", DEFAULT_CONNECTION_NAME))
  File "/usr/local/lib/python3.8/site-packages/mongoengine/connection.py", line 367, in get_db
    db.authenticate(
  File "/usr/local/lib/python3.8/site-packages/pymongo/database.py", line 1492, in authenticate
    self.client._cache_credentials(
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 775, in _cache_credentials
    server = self._get_topology().select_server(
  File "/usr/local/lib/python3.8/site-packages/pymongo/topology.py", line 241, in select_server
    return random.choice(self.select_servers(selector,
  File "/usr/local/lib/python3.8/site-packages/pymongo/topology.py", line 199, in select_servers
    server_descriptions = self._select_servers_loop(
  File "/usr/local/lib/python3.8/site-packages/pymongo/topology.py", line 215, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: mongo:27017: [Errno -5] No address associated with hostname, Timeout: 30s, Topology Description: <TopologyDescription id: 60056f33a2d6080b5aec4862, topology_type: Single, servers: [<ServerDescription ('mongo', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo:27017: [Errno -5] No address associated with hostname')>]>
```

**Comment by Jab2870** [comment]
I am not a python dev although it looks to me as though it is trying to connect
to a mongo db, despite specifying sqlite.

I would be happy to use mongo db if it wasn't for the fact that docs say it's
being depreciated.

**Comment by Casper9228** [comment]
I second this issue - can't complete the deployment of the container due to this.

**Comment by karabays** [comment]
the latest tag in docker hub is still I think older version. the sql is supported with v0.1 which is I believe dev tag in docker hub. so i tried pulling `hkotel/mealie:dev ` and seems like sqlite is working. but it is mentioned as release candidate, maybe wait little bit to switch from mongo to sql....

**Comment by Jab2870** [comment]
Thanks for the feedback. I can confirm that the dev branch starts. However, I
then get issue #86.

I wonder if the getting started documentation should be updated to reflect
this? Either it should advise use of mariadb for now or should advise the dev
branch

**Comment by hay-kot** [comment]
I've switched to a new CI/CD process for releases which appear to not I have worked... I'm investigating now hopefully I'll have an answer soon. Sorry everybody!

**Comment by Jab2870** [comment]
No need to apologize, I'm sure I speak for everyone by saying we're grateful
that you've put in the amount of work you already have to give us this amazing
tool.

**Comment by hay-kot** [comment]
Okay, I think I've got it. Looks like there was a bug with the parsing of the new time fields. Some recipes store them in time duration and that was messing with the data validation. It should now force whatever it gets into a string. Additionally, on commits to master, I was pushing to the dev branch on docker hub. That should be fixed now...currently in build and should be live in about an hour. I'm wokring on more integration tests to avoid these isues in the future.

**Comment by kirkybaby** [comment]
Working great again now, thanks!
