### ISSUE TITLE
[Bug] Issue with adding notes w/ sqlite

### ISSUE THREAD

**Issue by mdrichardson** [hay-kot/mealie#91]
When adding a note to a recipe that's in a sqlite db, the UI redirects to `http://<url>:9000/recipe/Internal%20Server%20Error`. The docker logs show:

```text
<clientIP>:57144 - "GET /api/recipe/Internal%20Server%20Error/ HTTP/1.1" 500
[2021-01-18 13:32:35 -0800] [9] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/routes/recipe_routes.py", line 50, in get_recipe
    recipe = Recipe.get_by_slug(recipe_slug)
  File "/app/services/recipe_services.py", line 97, in get_by_slug
    document = db.recipes.get(slug, "slug")
  File "/app/db/db_base.py", line 125, in get
    session.query(self.sql_model)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3500, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
<clientIP>:57146 - "GET /static/favicon.ico HTTP/1.1" 200
{"loglevel": "info", "workers": 6, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": null, "host": "0.0.0.0", "port": "80"}
Jobstore default:
    webhooks (trigger: cron[hour='0', minute='0'], next run at: 2021-01-19 00:00:00 PST)
    auto_backup_job (trigger: cron[hour='3'], next run at: 2021-01-19 03:00:00 PST)
<clientIP>:57145 - "GET /api/all-recipes/?keys=name&keys=slug&keys=image&keys=description&keys=dateAdded&keys=rating&num=100 HTTP/1.1" 200
[2021-01-18 13:32:35 -0800] [11] [INFO] Started server process [11]
[2021-01-18 13:32:35 -0800] [11] [INFO] Waiting for application startup.
[2021-01-18 13:32:35 -0800] [11] [INFO] Application startup complete.
[2021-01-18 13:32:35 -0800] [12] [INFO] Started server process [12]
[2021-01-18 13:32:35 -0800] [12] [INFO] Waiting for application startup.
[2021-01-18 13:32:35 -0800] [12] [INFO] Application startup complete.
[2021-01-18 13:32:35 -0800] [13] [INFO] Started server process [13]
[2021-01-18 13:32:35 -0800] [13] [INFO] Waiting for application startup.
[2021-01-18 13:32:35 -0800] [13] [INFO] Application startup complete.
[2021-01-18 13:32:35 -0800] [14] [INFO] Started server process [14]
[2021-01-18 13:32:35 -0800] [14] [INFO] Waiting for application startup.
[2021-01-18 13:32:35 -0800] [14] [INFO] Application startup complete.
<clientIP>:57145 - "GET / HTTP/1.1" 200
<clientIP>:57145 - "GET /api/all-recipes/?keys=name&keys=slug&keys=image&keys=description&keys=dateAdded&keys=rating&num=100 HTTP/1.1" 200
<clientIP>:57145 - "GET /static/favicon.ico HTTP/1.1" 200
{"loglevel": "info", "workers": 6, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": null, "host": "0.0.0.0", "port": "80"}
Jobstore default:
    webhooks (trigger: cron[hour='0', minute='0'], next run at: 2021-01-19 00:00:00 PST)
    auto_backup_job (trigger: cron[hour='3'], next run at: 2021-01-19 03:00:00 PST)
<clientIP>:57153 - "POST /api/recipe/create/ HTTP/1.1" 500
[2021-01-18 13:32:55 -0800] [12] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/routes/recipe_routes.py", line 81, in create_from_json
    created_recipe = data.save_to_db()
  File "/app/services/recipe_services.py", line 116, in save_to_db
    recipe_doc = db.recipes.save_new(recipe_dict)
  File "/app/db/db_base.py", line 149, in save_new
    new_document = self.sql_model(**document)
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 433, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 430, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/app/db/sql/recipe_models.py", line 172, in __init__
    self.notes = [Note(note) for note in notes]
  File "/app/db/sql/recipe_models.py", line 172, in <listcomp>
    self.notes = [Note(note) for note in notes]
TypeError: __init__() takes 1 positional argument but 2 were given
{"loglevel": "info", "workers": 6, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": null, "host": "0.0.0.0", "port": "80"}
Jobstore default:
    webhooks (trigger: cron[hour='0', minute='0'], next run at: 2021-01-19 00:00:00 PST)
    auto_backup_job (trigger: cron[hour='3'], next run at: 2021-01-19 03:00:00 PST)
<clientIP>:57154 - "GET /api/recipe/Internal%20Server%20Error/ HTTP/1.1" 500
[2021-01-18 13:32:55 -0800] [13] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/routes/recipe_routes.py", line 50, in get_recipe
    recipe = Recipe.get_by_slug(recipe_slug)
  File "/app/services/recipe_services.py", line 97, in get_by_slug
    document = db.recipes.get(slug, "slug")
  File "/app/db/db_base.py", line 125, in get
    session.query(self.sql_model)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3500, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
```

**Steps to Reproduce:**

1. Start with a fresh docker-compose, sqlite, v0.1.0
2. In UI, create new recipe
3. Enter a title, save
4. Everything is fine
5. Edit the recipe, adding a note
6. Error.

**Notes**

This also seems to impact recipe import. Any recipes I had in the last `:latest` release (v0.0.2) imported fine unless it had notes, in which case it won't import. I can copy/paste the JSON from the recipe into a new one, but as soon as I add the `notes` JSON property, it gives the errors above.

I'm not sure if this is related, but if I edit the recipe in the UI in v0.0.2, the notes seem to display properly as something like:

```json
"notes": [
      {
        "title": "Spiciness",
        "text": "1/2 tsp cayenne is medium spicy...enough kick to make your nose run a tiny bit but not uncomfortable at all."
      }
    ],
```

However, if I go to Settings > Backup, then unzip the backup and look at `recipes/recipe-name.json`, the notes are nested within an additional array, like:

```json
"notes": [
 [
      {
        "title": "Spiciness",
        "text": "1/2 tsp cayenne is medium spicy...enough kick to make your nose run a tiny bit but not uncomfortable at all."
      }
]
    ],
```

**Comment by hay-kot** [comment]
There is an issue with the __init__ call in creating the database entry. I've resolved the issue locally. Doing some final testing to make sure I caught all the edge cases before pushing another hotfix. On another related note, I'm going to focus on improving/creating testing moving forward so I can catch these kinds of issues.

**Comment by hay-kot** [comment]
This should be resolved, thanks for letting me know! I now have test coverage for this as well. Yahoo!

**Comment by mdrichardson** [comment]
@hay-kot Awesome! Thanks for the quick work! I'll give it a test run pretty soon!

**Comment by mdrichardson** [comment]
@hay-kot Just wanted to confirm it all works great now, including recipe import. Thanks!
